DROP TABLE IF EXISTS STORED_DATABASE_CONNECTION;
DROP SEQUENCE IF EXISTS db_api_sequence;

create sequence db_api_sequence;

CREATE TABLE STORED_DATABASE_CONNECTION (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  hostname VARCHAR(50) NOT NULL,
  port INT NOT NULL,
  database_name VARCHAR(50) NOT NULL,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX DB_CONN_UK ON STORED_DATABASE_CONNECTION(name)
